// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMB__mnu_poMMSLyx8YupZqWFqRaQElX8',
    appId: '1:183761413524:web:63da1ce0d23f290ec05b81',
    messagingSenderId: '183761413524',
    projectId: 'ai-literacy-app',
    authDomain: 'ai-literacy-app.firebaseapp.com',
    storageBucket: 'ai-literacy-app.appspot.com',
    measurementId: 'G-QT5KXJ4G13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDv8YTb2NfYYL9hbIPfFamf0d6Jjq6q3o',
    appId: '1:183761413524:android:fef24e71ad8c6037c05b81',
    messagingSenderId: '183761413524',
    projectId: 'ai-literacy-app',
    storageBucket: 'ai-literacy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqBri9ZJ5A_wBG1N9mrgS-uhBMIRpSfI',
    appId: '1:183761413524:ios:1063b7922b3d401fc05b81',
    messagingSenderId: '183761413524',
    projectId: 'ai-literacy-app',
    storageBucket: 'ai-literacy-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbqBri9ZJ5A_wBG1N9mrgS-uhBMIRpSfI',
    appId: '1:183761413524:ios:428874bdc5213d68c05b81',
    messagingSenderId: '183761413524',
    projectId: 'ai-literacy-app',
    storageBucket: 'ai-literacy-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
